apiVersion: v1
kind: Secret
metadata:
  name: pgsecret
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: MSFXZWxjb21l
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres-svc"
  replicas: 1 # por defecto es 1
  selector:
    matchLabels:
      app: postgres # tiene que coincidir con .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: postgres # tiene que coincidir con .spec.selector.matchLabels
    spec:
      containers:
      - name: postgres
        image: postgres:12.2
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgsecret
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pgsecret
                key: username
          - name: POSTGRES_DB
            value: shipments
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi